<?php

return array
(
    'HISTORY' => array
    (
        'PAYMENT_RECEIVED' => 'Payment of <u>%1.2f</u> <u>%s</u> received from <u>%s</u>',
        'DOWNLOAD_FILES' => 'Customer downloaded file <u>%s</u>',
    ),
    
    'PRODUCT_STATUSES' => array
    (
        'SALE' => 'On sale',
        'SOLD' => 'Sold',
    ),
    
    'ORDER_TYPES' => array
    (
        'DOWNLOAD' => 'Download',
        'REDESIGN' => 'Redesign',
        'CUSTOM' => 'Custom',
    ),
    
    'ORDER_STATUSES' => array
    (
        'WAIT' => '<span class="red">Unpaid</span>',
        'PAID' => '<span class="green">Paid</span>',
        'WORK' => '<span class="blue">On work</span>',
        'DONE' => '<span class="grey">Completed</span>',
    ),

    'ENABLED' => array
    (
        'YES' => '<span class="green">Yes</span>',
        'NO' => '<span class="grey">No</span>',
    ),
    
    'DISCOUNT_DESTINATIONS' => array
    (
        'GENERAL' => 'General discount',
        'PRODUCT' => '<span class="grey">Product: </span><span class="green">%s</span>',
        'ACCOUNT' => '<span class="grey">Email: </span><span class="green">%s</span>',
    ),
);